### PR TITLE
Return undefined/default when requesting key nested under null value.

### LINKED ISSUE #9: Default is working wrong for nested null value
```js
import delve from 'dlv'

let obj = {
  a: {
    c: 1,
    d: undefined,
    e: null
  }
}

console.log(delve(obj, 'a.c', 'default')) // 1
console.log(delve(obj, 'a.c.f', 'default')) // default

console.log(delve(obj, 'a.d', 'default')) // default
console.log(delve(obj, 'a.d.f', 'default')) // default

console.log(delve(obj, 'a.e', 'default')) // null
console.log(delve(obj, 'a.e.f', 'default')) // null <- bug
```

The last one is nested key over `null` value, it doesn't exist but returns `null` instead of default value.

### PR DESCRIPTION
**Pull request by kalmbach**
Return undefined/default value when requesting for a key nested under a null value.

My logic for this change is:
If we reach an `undefined` object or the end of the key path (`p >= key.length`), we return the object in that position, if that object is `undefined` we return the `default` value, otherwise we rerturn the object. (including `null` values)

When we don't reach the end of the key path (`p < key.length`), it's because a value in between is `falsey`, in either case that mean the object at the end of the key path is unreachable (`undefined`) and we should return the default value.

[Closes #9]

### CODE REVIEW

**Comment by kalmbach** [comment]
I have solved the error reported by travis locally installing the `uglify-js` package (note the diff in the name => `uglifyjs`)

**Comment by developit** [comment]
Just a note - I'm pondering this PR and want to merge it, but it won't go into today's release.

**Comment by jacktuck** [comment]
Wouldn't changing the strict equality check be better; so you can check for null or undefined? 
```
0 == null
false

undefined == null
true
```

File: index.js [hunk 1]
```diff
@@ -2,5 +2,5 @@ export default function dlv(obj, key, def, p) {
 	p = 0;
 	key = key.split ? key.split('.') : key;
 	while (obj && p<key.length) obj = obj[key[p++]];
-	return obj===undefined ? def : obj;
-}
\ No newline at end of file
+	return (obj===undefined || p<key.length) ? def : obj;
```
Comment (jacktuck) [inline index.js]: Could we not just have `obj == undefined` here and drop the strict equality check? :)

Comment (kalmbach) [reply index.js]: I am not following, if we drop the strict equality check it will fail to return a defined key with a `null` value, and will return the default instead. For example:
```
var obj = { a: null }
delve(obj, "a", "foo")
=> "foo"
``` 
It should have returned `null`, it's a defined key. It should only return `undefined` when the key is not defined in the object.

The strict equality check is necessary to distinguish undefined keys from the defined keys with null values.
I hope this makes sense.

Comment (jacktuck) [reply index.js]: Yeah you're right

**Comment by bboydflo** [comment]
it would be nice to merge this in :)

**Comment by jawadst** [comment]
@developit Any chance to merge and release this?

**Comment by developit** [comment]
Yup. Need to check size.

**Comment by developit** [comment]
131 bytes means this is only 7 bytes added weight. I'm in.
